// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIR_aPpIANiks9G49MJQP3qb33y-kFopI',
    appId: '1:24234108585:web:1f89b18d215f31b728abb8',
    messagingSenderId: '24234108585',
    projectId: 'projeto-fiction',
    authDomain: 'projeto-fiction.firebaseapp.com',
    storageBucket: 'projeto-fiction.appspot.com',
    measurementId: 'G-VQWC0KDDFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtSyvncmWLPSABsgZwP1xkaE-trR5VU3M',
    appId: '1:24234108585:android:7f2dee51c66c1cd428abb8',
    messagingSenderId: '24234108585',
    projectId: 'projeto-fiction',
    storageBucket: 'projeto-fiction.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_9J5n2PoYKg3qGqG177Dq6D4qCfNsCjI',
    appId: '1:24234108585:ios:29c2c8edb185b2e428abb8',
    messagingSenderId: '24234108585',
    projectId: 'projeto-fiction',
    storageBucket: 'projeto-fiction.appspot.com',
    iosBundleId: 'com.example.projetoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_9J5n2PoYKg3qGqG177Dq6D4qCfNsCjI',
    appId: '1:24234108585:ios:4939a963f9eb06f428abb8',
    messagingSenderId: '24234108585',
    projectId: 'projeto-fiction',
    storageBucket: 'projeto-fiction.appspot.com',
    iosBundleId: 'com.example.projetoMobile.RunnerTests',
  );
}
